control_login:
    path:     /login
    defaults: { _controller: AppControlBundle:Security:login }

control_logout:
    path: /logout

control_default:
    path:     /
    defaults: { _controller: AppControlBundle:Default:index }

control_companies_list:
    path:     /companies/list/
    defaults: { _controller: AppControlBundle:Companies:list }

control_shops_list:
    path:     /shops/list/
    defaults: { _controller: AppControlBundle:Shops:list }

control_users_list:
    path:     /users/list/
    defaults: { _controller: AppControlBundle:Users:list }
