security:

    encoders:
        Library\UsersBundle\Entity\Users: bcrypt

    providers:
        our_db_provider:
            entity:
                class: LibraryUsersBundle:Users

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: control_login
                check_path: control_login
                default_target_path: control_default
            logout:
                path: control_logout
                target: control_default

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
